import type { Metadata } from "next";
import { Kumbh_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Header from "./components/header";
import Bg from "./components/bg";
import { GlobalProvider } from "./context/globalContext";

const geistKumbh = Kumbh_Sans({
  variable: "--font-kumbh-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistKumbh.variable}  antialiased`}>
        <GlobalProvider>
          <ThemeProvider defaultTheme="system">
            <main className="flex flex-col gap-11">
              <Header />
              {children}
            </main>
            <Bg />
          </ThemeProvider>
        </GlobalProvider>
      </body>
    </html>
  );
}
