import type { Metadata } from "next";
import { Kumbh_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Header from "./components/header";
import Bg from "./components/bg";

const geistKumbh = Kumbh_Sans({
  variable: "--font-kumbh-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistKumbh.variable}  antialiased`}>
        <ThemeProvider>
          <main className="flex flex-col gap-11">
            <Header />
            {children}
          </main>
          <Bg />
        </ThemeProvider>
      </body>
    </html>
  );
}
